import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Projects
        </h1>

        <div className={styles.grid}>
          <Link href="/projects/gas" className={styles.card}>
            <h2>Gas tracker &rarr;</h2>
          </Link>

          <Link href="/projects/devdiary" className={styles.card}>
            <h2>Dev diary &rarr;</h2>
          </Link>

        </div>
      </main>


    </div>
  )
}
